name: Develop CI Tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Analyze and Test Code
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.6.0/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run linter
        run: ktlint

      - name: Tests
        run: ./gradlew test
